package com.influx.pojo;

public class NodeInfo {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column m_node_info.node_id
     *
     * @abatorgenerated
     */
    private String nodeId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column m_node_info.node_name
     *
     * @abatorgenerated
     */
    private String nodeName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column m_node_info.node_type
     *
     * @abatorgenerated
     */
    private Integer nodeType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column m_node_info.parent_node
     *
     * @abatorgenerated
     */
    private String parentNode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column m_node_info.node_x
     *
     * @abatorgenerated
     */
    private Integer nodeX;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column m_node_info.node_y
     *
     * @abatorgenerated
     */
    private Integer nodeY;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column m_node_info.node_cls
     *
     * @abatorgenerated
     */
    private Integer nodeCls;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column m_node_info.node_style
     *
     * @abatorgenerated
     */
    private Integer nodeStyle;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column m_node_info.node_rule
     *
     * @abatorgenerated
     */
    private String nodeRule;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column m_node_info.node_mach
     *
     * @abatorgenerated
     */
    private String nodeMach;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column m_node_info.node_sucess_rate
     *
     * @abatorgenerated
     */
    private Integer nodeSucessRate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column m_node_info.continue_fail_count
     *
     * @abatorgenerated
     */
    private Integer continueFailCount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column m_node_info.war
     *
     * @abatorgenerated
     */
    private String war;

    public String getNodeId() {
        return nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    public String getNodeName() {
        return nodeName;
    }

    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    public Integer getNodeType() {
        return nodeType;
    }

    public void setNodeType(Integer nodeType) {
        this.nodeType = nodeType;
    }

    public String getParentNode() {
        return parentNode;
    }

    public void setParentNode(String parentNode) {
        this.parentNode = parentNode;
    }

    public Integer getNodeX() {
        return nodeX;
    }

    public void setNodeX(Integer nodeX) {
        this.nodeX = nodeX;
    }

    public Integer getNodeY() {
        return nodeY;
    }

    public void setNodeY(Integer nodeY) {
        this.nodeY = nodeY;
    }

    public Integer getNodeCls() {
        return nodeCls;
    }

    public void setNodeCls(Integer nodeCls) {
        this.nodeCls = nodeCls;
    }

    public Integer getNodeStyle() {
        return nodeStyle;
    }

    public void setNodeStyle(Integer nodeStyle) {
        this.nodeStyle = nodeStyle;
    }

    public String getNodeRule() {
        return nodeRule;
    }

    public void setNodeRule(String nodeRule) {
        this.nodeRule = nodeRule;
    }

    public String getNodeMach() {
        return nodeMach;
    }

    public void setNodeMach(String nodeMach) {
        this.nodeMach = nodeMach;
    }

    public Integer getNodeSucessRate() {
        return nodeSucessRate;
    }

    public void setNodeSucessRate(Integer nodeSucessRate) {
        this.nodeSucessRate = nodeSucessRate;
    }

    public Integer getContinueFailCount() {
        return continueFailCount;
    }

    public void setContinueFailCount(Integer continueFailCount) {
        this.continueFailCount = continueFailCount;
    }

    public String getWar() {
        return war;
    }

    public void setWar(String war) {
        this.war = war;
    }
}
